openapi: 3.0.0
info:
  title: Sample API
  description: API Documentation for managing users MS
  version: 1.0.0
servers:
  - url: '/user-management'
    description: Optional server description, e.g. Main (production) server

paths:
  /user:
    get:
      summary: Returns a user by ID.
      tags:
        - user
      operationId: getUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /users:
    get:
      summary: Returns users list.
      tags:
        - users
      operationId: getUsers
      responses:
        '200':
          description: A users object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

components:
  schemas:

    UsersResponse:
      title: Users Response
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'

    UserResponse:
      title: Users Response
      type: object
      properties:
        first_name:
          type: string
        id:
          type: integer
          format: int64
      required:
        - first_name
        - id

    UserRequest:
      title: Users Request
      type: object
      description: Users Request
      properties:
        idUser:
          type: String
          minLength: 1
          maxLength: 10